export const componentLists: Record<string, string[]> = {
  reactbits: [
    "animated-content", "animated-list", "antigravity", "ascii-text", "aurora",
    "balatro", "ballpit", "beams", "blob-cursor", "blur-text", "border-glow",
    "bounce-cards", "bubble-menu", "card-nav", "card-swap", "chroma-grid",
    "circular-gallery", "click-spark", "color-bends", "count-up", "counter",
    "crosshair", "cubes", "curved-loop", "dark-veil", "decay-card",
    "decrypted-text", "dither", "dome-gallery", "dot-field", "dot-grid",
    "elastic-slider", "electric-border", "evil-eye", "fade-content",
    "falling-text", "faulty-terminal", "floating-lines", "flowing-menu",
    "fluid-glass", "flying-posters", "folder", "fuzzy-text", "galaxy",
    "ghost-cursor", "glare-hover", "glass-icons", "glass-surface", "glitch-text",
    "gooey-nav", "gradient-blinds", "gradient-text", "gradual-blur", "grainient",
    "grid-distortion", "grid-motion", "grid-scan", "hyperspeed", "image-trail",
    "infinite-scroll", "iridescence", "lanyard", "laser-flow", "letter-glitch",
    "light-pillar", "light-rays", "lightning", "line-waves", "liquid-chrome",
    "liquid-ether", "logo-loop", "magic-bento", "magic-rings", "magnet",
    "magnet-lines", "masonry", "meta-balls", "metallic-paint", "model-viewer",
    "noise", "orb", "orbit-images", "particles", "pill-nav", "pixel-blast",
    "pixel-card", "pixel-snow", "pixel-transition", "plasma", "plasma-wave",
    "prism", "prismatic-burst", "profile-card", "radar", "rb-carousel", "rb-dock",
    "rb-pixel-trail", "reflective-card", "ribbons", "ripple-grid", "rotating-text",
    "scrambled-text", "scroll-float", "scroll-reveal", "scroll-stack",
    "scroll-velocity", "shape-blur", "shape-grid", "shiny-text", "shuffle",
    "silk", "soft-aurora", "splash-cursor", "split-text", "spotlight-card",
    "stack", "staggered-menu", "star-border", "stepper", "sticker-peel",
    "target-cursor", "text-cursor", "text-pressure", "text-type", "threads",
    "tilted-card", "true-focus", "variable-proximity", "waves",
  ],
  "cult-ui": [
    "ai-instructions", "animated-number", "bg-animate-button",
    "bg-animated-fractal-grid", "bg-animated-gradient", "bg-image-texture",
    "bg-media", "border-beam-button", "canvas-fractal-grid", "choice-poll",
    "code-block", "color-picker", "cosmic-button", "cult-popover", "cutout-card",
    "direction-aware-tabs", "distorted-glass", "dither-image", "dock",
    "dynamic-island", "edge-blur", "expandable", "expandable-screen",
    "family-button", "family-drawer", "feature-carousel", "feature-poll",
    "feature-voting", "floating-panel", "gradient-button-group", "gradient-heading",
    "grid-beam", "hero-color-panel", "hero-dithering", "hero-heatmap",
    "hero-liquid-metal", "hero-static-radial-gradient", "hover-video-player",
    "intro-disclosure", "lightboard", "loading-carousel", "logo-carousel",
    "metal-button", "minimal-card", "morph-surface", "neumorph-button",
    "neumorph-eyebrow", "onboarding", "pixel-heading-character",
    "pixel-heading-word", "pixel-paragraph-words", "pixel-paragraph-words-inverse",
    "poll-widget", "popover-form", "prompt-library", "shader-lens-blur",
    "shift-card", "side-panel", "sortable-list", "squiggle-arrow",
    "stripe-bg-guides", "svg-bands", "svg-shapes", "svg-shapes-animated",
    "terminal-animation", "text-animate", "text-gif", "texture-button",
    "texture-card", "texture-overlay", "three-d-carousel", "timer",
    "toolbar-expandable", "tweet-grid", "typewriter", "vote-tally",
    "youtube-video-player",
  ],
  fancy: [
    "animated-gradient-with-svg", "basic-number-ticker", "box-carousel",
    "breathing-text", "circling-elements", "circular-text", "css-box",
    "cursor-attractor", "drag-elements", "elastic-line", "fancy-typewriter",
    "float", "gooey-svg-filter", "gravity", "image-trail", "letter-3d-swap",
    "letter-swap", "letter-swap-hover", "marquee", "marquee-along-svg-path",
    "media-between-text", "parallax-floating", "pixel-trail",
    "pixelate-svg-filter", "random-letter-swap-hover", "scramble-hover",
    "scramble-in", "screensaver", "scroll-and-swap", "stacking-cards",
    "text-along-path", "text-cursor-proximity", "text-highlighter", "text-rotate",
    "underline-animation", "underline-to-background", "variable-font",
    "variable-font-and-cursor", "variable-font-hover-by-letter",
    "variable-font-hover-by-random-letter", "vertical-cut-reveal",
  ],
  kokonutui: [
    "action-search-bar", "ai-input-search", "ai-loading", "ai-prompt",
    "ai-text-loading", "ai-voice", "apple-activity-card", "attract-button",
    "aurora-background", "avatar-picker", "background-paths", "beams-background",
    "bento-grid", "card-flip", "card-stack", "carousel-cards", "command-button",
    "currency-transfer", "dynamic-text", "file-upload", "flow-field",
    "gradient-button", "hold-button", "kokonut-glitch-text", "kokonut-typewriter",
    "liquid-glass-card", "loader", "magnetic-button", "matrix-text",
    "morphic-navbar", "mouse-effect-card", "particle-button", "profile-dropdown",
    "scroll-text", "shape-hero", "shimmer-text", "sliced-text",
    "slide-text-button", "smooth-drawer", "smooth-tab", "social-button",
    "spotlight-cards", "submit-button", "switch-button", "swoosh-text",
    "team-selector", "toolbar", "tweet-card", "v0-button",
  ],
  "paper-shaders": [
    "color-panels", "dithering", "dot-grid", "dot-orbit", "fluted-glass",
    "gem-smoke", "god-rays", "grain-gradient", "halftone-cmyk", "halftone-dots",
    "heatmap", "image-dithering", "liquid-metal", "mesh-gradient", "metaballs",
    "neuro-noise", "paper-texture", "perlin-noise", "pulsing-border",
    "simplex-noise", "smoke-ring", "spiral", "static-mesh-gradient",
    "static-radial-gradient", "swirl", "voronoi", "warp", "water", "waves",
  ],
};
